### ISSUE TITLE
opam compiler fails with unknown algorithm

### ISSUE THREAD

**Issue by mattpallissard** [ocaml-opam/opam-compiler#9]
It seems that all commands handed to opam compiler fail with "Fatal error: exception (Failure "Unknown algorithm 1.3.101.112")"

That oid appears to indicate Edwards-curve Digital Signature Algorithm (EdDSA) Ed25519 

Let me know what other information you may need.  Thanks in advance.

```
~  opam --version
2.0.7
~  ocaml --version
The OCaml toplevel, version 4.11.1
```

```
~  opam pin add opam-compiler 'git+https://github.com/emillon/opam-compiler.git'
[opam-compiler.0.1.1] synchronised from git+https://github.com/emillon/opam-compiler.git
opam-compiler is now pinned to git+https://github.com/emillon/opam-compiler.git (version 0.1.1)

The following actions will be performed:
  ↻ recompile opam-compiler 0.1.1*
Do you want to continue? [Y/n] y
[opam-compiler.0.1.1] synchronised from git+https://github.com/emillon/opam-compiler.git

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⊘ removed   opam-compiler.0.1.1
∗ installed opam-compiler.0.1.1
Done.
# Run eval $(opam env) to update the current shell environment
```
```
~  opam compiler create '#1234'
Fatal error: exception (Failure "Unknown algorithm 1.3.101.112")
```

**Comment by mattpallissard** [comment]
I wound up digging into this and tracked this down to the ocaml-x509 package.  Sorry for the noise.

**Comment by emillon** [comment]
No problem. I'm keeping that open because there are a couple improvements we can do in the compiler itself:
- display that as a TLS error
- fallback to a simpler behavior if possible (for example, if asking the PR description to github fails, we can just not set a description instead)

**Comment by mattpallissard** [comment]
Thanks, and as an FYI, once [this PR](https://github.com/mirleft/ocaml-x509/pull/136) is merged the issue I was referring to is mitigated.

**Comment by hannesm** [comment]
FWIW, with ca-certs 0.1.3 released (to opam-repository https://github.com/ocaml/opam-repository/pull/17646) this issue disappears. ca-certs 0.1.3 is more resilient to certificate decoding issues. sorry for the inconvenience -- and of course the improvements https://github.com/ocaml-opam/opam-compiler/issues/9#issuecomment-723883318 can still apply.
